version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    volumes:
      - db-data:/foo
volumes:
  db-data: 